[build]
  base = "frontend"
  command = "npm run build"
  functions = "frontend/netlify/functions"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"

# Uncomment to use this redirect for Single Page Applications like create-react-app.
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200